//! Static lookup tables for the PKWARE Data Compression Library (DCL) "implode"/"explode"
//! format. These exact values are dictated by the compressed bitstream format itself - any
//! compatible encoder/decoder pair must agree on them.

pub(crate) const COPY_OFFSET_BITS: [u8; 64] = [
    2, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
];

pub(crate) const COPY_OFFSET_CODE: [u8; 64] = [
    0x03, 0x0D, 0x05, 0x19, 0x09, 0x11, 0x01, 0x3E, 0x1E, 0x2E, 0x0E, 0x36, 0x16, 0x26, 0x06, 0x3A, 0x1A, 0x2A, 0x0A, 0x32, 0x12, 0x22,
    0x42, 0x02, 0x7C, 0x3C, 0x5C, 0x1C, 0x6C, 0x2C, 0x4C, 0x0C, 0x74, 0x34, 0x54, 0x14, 0x64, 0x24, 0x44, 0x04, 0x78, 0x38, 0x58, 0x18,
    0x68, 0x28, 0x48, 0x08, 0xF0, 0x70, 0xB0, 0x30, 0xD0, 0x50, 0x90, 0x10, 0xE0, 0x60, 0xA0, 0x20, 0xC0, 0x40, 0x80, 0x00,
];

pub(crate) const COPY_LENGTH_BASE_BITS: [u8; 16] = [3, 2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7];

pub(crate) const COPY_LENGTH_BASE_VALUE: [u16; 16] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x0A, 0x0E, 0x16, 0x26, 0x46, 0x86, 0x106,
];

pub(crate) const COPY_LENGTH_BASE_CODE: [u8; 16] = [
    0x05, 0x03, 0x01, 0x06, 0x0A, 0x02, 0x0C, 0x14, 0x04, 0x18, 0x08, 0x30, 0x10, 0x20, 0x40, 0x00,
];

pub(crate) const COPY_LENGTH_EXTRA_BITS: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8];

/// Codeword table index reserved as the end-of-stream marker: `COPY_LENGTH_BASE_VALUE[15] + 255 == 517`,
/// one past the maximum real copy length (516), so it can never collide with an actual copy-length code.
pub(crate) const EOF_CODE_INDEX: usize = 773;

/// Total size of the combined literal + copy-length codeword table (256 literals + 518 length codes).
pub(crate) const CODEWORD_COUNT: usize = 774;

/// Maximum length of a single copy (back-reference) match.
pub(crate) const MAX_REP_LENGTH: usize = 516;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn eof_code_index_matches_table_layout() {
        // code_index starts at 256 and advances by (1 << extra_bits) for each of the 16 length
        // classes; EOF is the very last entry generated by that loop.
        let mut code_index = 256usize;
        for extra_bits in COPY_LENGTH_EXTRA_BITS {
            code_index += 1usize << extra_bits;
        }
        assert_eq!(code_index, CODEWORD_COUNT);
        assert_eq!(code_index - 1, EOF_CODE_INDEX);
    }
}
